spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-yw-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-yw-test
